theme: jekyll-theme-minimal
title: wandererbio
description: Social Entrepreneur, Technologist, Global Citizen, Shutterbug and Wanderer.
<script data-ad-client="ca-pub-7942490529687454" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
