theme: jekyll-theme-minimal
title: wandererbio
author: marahmann
description: Entrepreneur, Researcher, Software Engineer, Global Citizen, Shutterbug and Wanderer.
url: https://wandererbio.com
blog: https://blog.wandererbio.com
